name: Hello World
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        default: world
        required: false
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello ${{ inputs.name }}"

